version: 0.2

phases:
  build:
    commands:
      - sam build -t template.yml

  post_build:
    commands:
      - |
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
        --s3-bucket $CODEPIPELINE_BUCKET \
        --s3-prefix $STACK_NAME \
        --region $AWS_REGION \
        --stack-name $STACK_NAME \
        --capabilities CAPABILITY_IAM \
        --parameter-overrides \
        Environment=$ENVIRONMENT
      -
        sam publish -t template.yml

